---
- name: Syncronize configuration
  copy:     
    src: "{{ item }}"
    dest: "/{{ item }}"
  with_items:
    - usr/local/nagios/dell/config/objects/10.150.4.64.cfg
    - usr/local/nagios/dell/config/templates/dell_contacts.cfg
  notify:
    - nagios_restart
