---
- name: Setup Dell Linux Independent Repository
  yum_repository:
    name: dell-system-update_independent
    state: present
    baseurl: http://linux.dell.com/repo/hardware/latest/os_independent/
    description: dell-system-update_independent
    gpgkey: http://linux.dell.com/repo/hardware/latest/public.key,http://linux.dell.com/repo/hardware/latest/public_gpg3.key

- name: Setup Dell Linux Dependent Repository
  yum_repository:
    name: dell-system-update_dependent
    state: present
    baseurl: http://linux.dell.com/repo/hardware/latest/os_dependent/RHEL7_64/
    description: dell-system-update_dependent
    gpgkey: http://linux.dell.com/repo/hardware/latest/public.key,http://linux.dell.com/repo/hardware/latest/public_gpg3.key