---
- name: Assures the existance of the ilo plugin config directory.
  file:
    path: "/usr/local/nagios/etc/ilo"
    state: directory

- name: Assures the existance of the nagios credentials directory.
  file:
    path: "/etc/nagios"
    state: directory

- name: Synchronize configuration
  copy:     
    src: "{{ item }}"
    dest: "/{{ item }}"
  with_items:
    - usr/local/nagios/etc/ilo/ilo.cfg
    - etc/nagios/.nagios_restful_credential.tdb
  notify:
    - nagios_restart

- name: Correct permissions of nagios-credentials file
  file:
    path: /etc/nagios/.nagios_restful_credential.tdb
    mode:  0600
    owner: nagios
    group: nagios